name: Cloud Security Scan
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Scan container images
        uses: aquasec/trivy-action@master
        with:
          image-ref: 'nginx:latest'  # Test with a public image
          format: 'json'
          output: 'trivy-results.json'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Scan IaC
        run: |
          trivy config --severity CRITICAL,HIGH --format json --output trivy-iac.json ./iac/

  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./iac/
          output_format: json
          output_file_path: checkov-results.json

  ai-remediation:
    runs-on: ubuntu-latest
    needs: [trivy-scan, checkov-scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate AI Fixes
        run: |
          pip install openai
          python3 scripts/ai-remediation.py --trivy trivy-results.json --checkov checkov-results.json
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  report:
    runs-on: ubuntu-latest
    needs: [ai-remediation]
    steps:
      - name: Generate Report
        run: |
          python3 scripts/generate-report.py
      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: report.html