name: Cloud Security Assessment Pipeline

on:
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Scan Type (full, iac-only, compliance-only, container-only, policy-only)'
        required: true
        default: 'full'
      clients:
        description: 'Comma-separated list of client names (e.g., client-a,client-b)'
        required: true
        default: 'test-client'
      resource_groups:
        description: 'Comma-separated list of resource groups/projects (e.g., rg-a,rg-b)'
        required: true
        default: 'test-rg'

env:
  SCAN_TYPE: ${{ github.event.inputs.scan_type }}

jobs:
  security-scan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - client: client-a
            resource_group: rg-a
          - client: client-b
            resource_group: rg-b

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create required directories
        run: mkdir -p results report generated-policies

      - name: Install Tools (Trivy, Conftest, Gitleaks, Python)
        run: |
          # ✅ Install Trivy
          curl -L https://github.com/aquasecurity/trivy/releases/download/v0.42.0/trivy_0.42.0_Linux-64bit.tar.gz -o trivy.tar.gz
          tar -xvzf trivy.tar.gz
          sudo mv trivy /usr/local/bin/trivy

          # ✅ Install Conftest (raw binary)
          curl -L https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_Linux_x86_64 -o conftest
          chmod +x conftest && sudo mv conftest /usr/local/bin/conftest

          # ✅ Install Gitleaks safely
          GITLEAKS_VERSION=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | grep tag_name | cut -d '"' -f 4)
          curl -L "https://github.com/gitleaks/gitleaks/releases/download/${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION#v}_linux_x64.tar.gz" -o gitleaks.tar.gz
          tar -xvzf gitleaks.tar.gz gitleaks
          chmod +x gitleaks && sudo mv gitleaks /usr/local/bin/gitleaks

          # ✅ Install Python, pip, and PDF libs
          sudo apt-get update && sudo apt-get install -y python3 python3-pip libpangocairo-1.0-0
          pip3 install --no-cache-dir openai weasyprint jinja2

      - name: Trivy Config and Image Scan
        if: env.SCAN_TYPE == 'full' || env.SCAN_TYPE == 'container-only'
        run: |
          trivy config ./iac --format json --output results/trivy-config-results.json
          trivy image alpine:latest --format json --output results/trivy-image-results.json

      - name: Secrets Scan with Gitleaks
        if: env.SCAN_TYPE == 'full' || env.SCAN_TYPE == 'iac-only'
        run: |
          gitleaks detect --source . --report-path results/gitleaks-results.json --report-format json

      - name: Dependency Vulnerability Scan
        if: env.SCAN_TYPE == 'full' || env.SCAN_TYPE == 'container-only'
        run: |
          trivy fs . --scanners vuln,license,secret --format json --output results/trivy-dependency-results.json

      - name: Checkov IaC Security Scan
        if: env.SCAN_TYPE == 'full' || env.SCAN_TYPE == 'iac-only'
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./iac/
          output_format: json
          output_file_path: results/checkov-results.json

      - name: Regula Terraform Compliance Scan
        if: env.SCAN_TYPE == 'full' || env.SCAN_TYPE == 'iac-only'
        run: |
          curl -sSL https://github.com/fugue/regula/releases/download/v3.1.0/regula-linux-amd64.tar.gz | tar xz
          ./regula run ./iac/ --format json > results/regula-results.json || echo '{"results":[]}' > results/regula-results.json

      - name: Prowler AWS Compliance Scan
        if: env.SCAN_TYPE == 'full' || env.SCAN_TYPE == 'compliance-only'
        run: |
          git clone https://github.com/prowler-cloud/prowler
          cd prowler
          ./prowler aws --output json --output-file ../results/prowler-aws-results.json

      - name: Validate OPA Policies
        run: |
          conftest test ./generated-policies/${{ matrix.client }}/ || echo "Conftest validation failed"

      - name: AI Remediation & Compliance Explanation
        run: |
          python3 scripts/AI-Remediation.py \
            --trivy "results/trivy-*-results.json" \
            --checkov "results/checkov-results.json" \
            --client "${{ matrix.client }}" \
            --resource-group "${{ matrix.resource_group }}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: AI-Generated Custom Policies
        run: |
          python3 scripts/AI-Policy-Generator.py \
            --ai "ai-remediation-results-${{ matrix.client }}.json" \
            --client "${{ matrix.client }}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Upload AI-Generated Policies
        uses: actions/upload-artifact@v4
        with:
          name: ai-policies-${{ matrix.client }}
          path: generated-policies/${{ matrix.client }}

      - name: Generate Client Report (PDF)
        run: |
          python3 scripts/generate-report.py \
            --trivy "results/trivy-*-results.json" \
            --checkov "results/checkov-results.json" \
            --opa "results/opa-results.json" \
            --conftest "results/conftest-results.json" \
            --ai "ai-remediation-results-${{ matrix.client }}.json" \
            --client "${{ matrix.client }}" \
            --resource-group "${{ matrix.resource_group }}"
          weasyprint report/report.html report/report-${{ matrix.client }}.pdf

      - name: Upload Security Report and Results
        uses: actions/upload-artifact@v4
        with:
          name: security-report-${{ matrix.client }}
          path: |
            report/report-${{ matrix.client }}.pdf
            results/





# ================================================
# ⚙️ REMINDERS FOR CLIENT ASSESSMENT:
# 1. Update matrix "client/resource_group" pairs for each new client.
# 2. Set OPENAI_API_KEY in GitHub repo secrets.
# 3. Select proper scan_type when launching (full, iac-only, compliance-only, etc.).
# 4. Update tool versions in download URLs only if necessary.
# 5. Customize report_template/security-report-template.html for branding.
# 6. Ensure results/ and generated-policies/ are in .gitignore to avoid committing.
# ================================================

