name: Cloud Security Assessment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allows manual triggers for add-ons
    inputs:
      run_compliance:
        description: 'Run compliance scan (extra charge)'
        required: false
        default: 'false'

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Container Scan
        uses: aquasec/trivy-action@master
        with:
          image-ref: '${{ vars.CLIENT_IMAGE }}'
          format: 'json'
          output: 'trivy-container-results.json'
          severity: 'CRITICAL,HIGH'

      - name: IaC Scan
        run: |
          trivy config --severity CRITICAL,HIGH --format json \
          --output trivy-iac-results.json ./iac/

  checkov-scan:
    runs-on: ubuntu-latest
    needs: [trivy-scan]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: IaC Policy Check
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ./iac/
          output_format: json
          output_file_path: checkov-results.json

  # ==============================================
  # COMPLIANCE ADD-ON (Uncomment for paid tier)
  # ----------------------------------------------
  # scout-suite:
  #   runs-on: ubuntu-latest
  #   needs: [trivy-scan]
  #   if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_compliance == 'true' }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  # 
  #     - name: AWS Compliance Audit
  #       run: |
  #         docker run -v $(pwd):/app/scoutsuite-results \
  #           -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY }} \
  #           -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY }} \
  #           scoutsuite/scoutsuite scout.py aws
  # 
  #     - name: Archive Results
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: scoutsuite-report
  #         path: scoutsuite-results/
  # ==============================================

  ai-remediation:
    runs-on: ubuntu-latest
    needs: [trivy-scan, checkov-scan]
    steps:
      - name: Generate AI Fixes
        run: |
          pip install openai
          python3 scripts/ai-remediation.py \
            --trivy trivy-*-results.json \
            --checkov checkov-results.json
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  report:
    runs-on: ubuntu-latest
    needs: [ai-remediation]  # Add 'scout-suite' here if enabling compliance
    steps:
      - name: Generate Report
        run: python3 scripts/generate-report.py

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: report.html